name: Déploiement - Développement

on:
  push:
    branches:
      - Developpement
jobs:
  deploiement-developpement:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copie du repertoire via SCP
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "*"
        target: "/var/www/developpement/ticket-tac/api"

    - name: Execution de commandes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: ls
